/**
 * Master packing list for AI-Powered Packing Checklist
 * Organized by category, with type safety for easy extension and customization.
 */

/**
 * Represents a master packing item definition for templates and AI logic.
 * Used for the master list, not for user-specific packing lists.
 * @property {string} name - Name of the item (e.g., "T-shirts").
 * @property {boolean} [essential] - Whether this item is typically essential.
 * @property {number} [defaultQuantity] - Default quantity suggested (optional).
 * @property {string[]} [tags] - Tags for filtering/templates (e.g., ['beach', 'business']).
 */
export type MasterPackingItem = {
  /** Name of the item (e.g., "T-shirts") */
  name: string;
  /** Whether this item is typically essential */
  essential?: boolean;
  /** Default quantity suggested (optional) */
  defaultQuantity?: number;
  /** Tags for filtering/templates (e.g., ['beach', 'business']) */
  tags?: string[];
};

export type PackingCategory = {
  /** Category name (e.g., "Clothing") */
  category: string;
  /** List of items in this category */
  items: MasterPackingItem[];
};

/**
 * The master list of packing categories and items.
 * Extend or customize as needed for templates or AI logic.
 */
export const PACKING_MASTER_LIST: PackingCategory[] = [
  {
    category: 'Clothing',
    items: [
      { name: 'T-shirts', essential: true, defaultQuantity: 3 },
      { name: 'Dress shirts/blouses' },
      { name: 'Casual shirts/tops' },
      { name: 'Tank tops/camisoles' },
      { name: 'Sweaters/hoodies' },
      { name: 'Fleece/jumper' },
      { name: 'Pants/jeans' },
      { name: 'Shorts/skirts' },
      { name: 'Dresses' },
      { name: 'Leggings/yoga pants' },
      { name: 'Undergarments', essential: true, defaultQuantity: 5 },
      { name: 'Sports bras' },
      { name: 'Socks', essential: true, defaultQuantity: 5 },
      { name: 'Compression socks' },
      { name: 'Sleepwear/pajamas' },
      { name: 'Swimsuit' },
      { name: 'Swim cover-up' },
      { name: 'Light jacket' },
      { name: 'Heavy jacket/coat' },
      { name: 'Rain jacket/umbrella' },
      { name: 'Packable down jacket' },
      { name: 'Belt' },
      { name: 'Hat/cap' },
      { name: 'Beanie/winter hat' },
      { name: 'Scarf/gloves' },
      { name: 'Workout clothes' },
      { name: 'Formalwear' },
      { name: 'Tie/bowtie' },
      { name: 'Thermal underwear/base layers' },
      { name: 'Cover-up/sarong', tags: ['beach', 'pool', 'women', 'unisex'] },
      { name: 'Rash guard', tags: ['beach', 'water sports', 'unisex'] },
      { name: 'Board shorts', tags: ['beach', 'water sports', 'men', 'unisex'] },
      { name: 'Bikini/tankini', tags: ['beach', 'women'] },
      { name: 'One-piece swimsuit', tags: ['beach', 'women'] },
      { name: 'Swim trunks', tags: ['beach', 'men'] },
      { name: 'Swim cap', tags: ['pool', 'all'] },
      { name: 'Sun hat/wide-brim hat', tags: ['beach', 'women', 'unisex'] },
      { name: 'Sundress', tags: ['beach', 'casual', 'women'] },
      { name: 'Maxi dress', tags: ['beach', 'casual', 'women'] },
      { name: 'Romper/jumpsuit', tags: ['women'] },
      { name: 'Crop tops', tags: ['women'] },
      { name: 'Sports hijab', tags: ['active', 'women'] },
      { name: 'Abaya', tags: ['cultural', 'women'] },
      { name: 'Kaftan', tags: ['beach', 'cultural', 'women'] },
      { name: 'Sarong/lungi', tags: ['beach', 'cultural', 'men', 'unisex'] },
      { name: 'Suit jacket/blazer', tags: ['business', 'all'] },
      { name: 'Dress pants/skirt', tags: ['business', 'all'] },
      { name: 'Dress (business)', tags: ['business', 'women'] },
      { name: 'Blouse', tags: ['business', 'women'] },
      { name: 'Polo shirt', tags: ['business', 'casual', 'men'] },
      { name: 'Cufflinks', tags: ['business', 'men'] },
      { name: 'Tights/stockings', tags: ['business', 'formal', 'women'] },
      { name: 'Shawl/pashmina', tags: ['formal', 'cultural', 'women'] },
      { name: 'Ski jacket', tags: ['ski', 'snow', 'all'] },
      { name: 'Ski pants', tags: ['ski', 'snow', 'all'] },
      { name: 'Base layers/thermal leggings', tags: ['ski', 'snow', 'all'] },
      { name: 'Snow boots', tags: ['ski', 'snow', 'all'] },
      { name: 'Ski gloves/mittens', tags: ['ski', 'snow', 'all'] },
      { name: 'Neck gaiter/balaclava', tags: ['ski', 'snow', 'all'] },
      { name: 'Festival outfit/costume', tags: ['festival', 'all'] },
      { name: 'Yoga pants/leggings', tags: ['wellness', 'retreat', 'women'] },
      { name: 'Sports skirt/skort', tags: ['active', 'women'] },
      { name: 'Nursing bra', tags: ['maternity', 'women'] },
      { name: 'Maternity wear', tags: ['pregnant', 'women'] },
      { name: 'Compression leggings', tags: ['long flights', 'all'] },
      { name: 'Rain poncho', tags: ['outdoor', 'all'] },
      { name: 'Fishing vest', tags: ['outdoor', 'all'] },
      { name: 'Hiking shorts', tags: ['outdoor', 'all'] },
      { name: 'Quick-dry shirt', tags: ['outdoor', 'all'] },
      { name: 'Climbing pants', tags: ['adventure', 'all'] },
      { name: 'Cycling shorts/jersey', tags: ['cycling', 'all'] },
      { name: 'Riding boots', tags: ['equestrian', 'all'] },
      { name: 'Wetsuit', tags: ['diving', 'surfing', 'all'] },
    ],
  },
  {
    category: 'Footwear',
    items: [
      { name: 'Sneakers/walking shoes', essential: true },
      { name: 'Sandals/flip-flops' },
      { name: 'Dress shoes' },
      { name: 'Boots' },
      { name: 'Water shoes' },
      { name: 'Slippers/house shoes' },
      { name: 'Shoe insoles' },
      { name: 'Shoe bags' },
      { name: 'Flip-flops', tags: ['beach', 'all'] },
      { name: 'Water sandals', tags: ['beach', 'all'] },
      { name: 'Heels', tags: ['formal', 'women'] },
      { name: 'Ballet flats', tags: ['casual', 'formal', 'women'] },
      { name: 'Loafers', tags: ['business', 'casual', 'men'] },
      { name: 'Espadrilles', tags: ['summer', 'all'] },
      { name: 'Clogs', tags: ['wellness', 'spa', 'all'] },
      { name: 'Snow boots', tags: ['ski', 'snow', 'all'] },
      { name: 'Cleats', tags: ['sports', 'all'] },
      { name: 'Riding boots', tags: ['equestrian', 'all'] },
    ],
  },
  {
    category: 'Toiletries',
    items: [
      { name: 'Toothbrush & toothpaste', essential: true },
      { name: 'Floss' },
      { name: 'Mouthwash' },
      { name: 'Deodorant', essential: true },
      { name: 'Shampoo/conditioner' },
      { name: 'Dry shampoo' },
      { name: 'Soap/body wash' },
      { name: 'Face wash/cleanser' },
      { name: 'Moisturizer' },
      { name: 'Razor & shaving cream' },
      { name: 'Hairbrush/comb' },
      { name: 'Hair ties/clips' },
      { name: 'Hair gel/spray' },
      { name: 'Skincare products' },
      { name: 'Sunscreen' },
      { name: 'Lip balm' },
      { name: 'Makeup' },
      { name: 'Makeup remover' },
      { name: 'Feminine hygiene products' },
      { name: 'Nail clippers/tweezers' },
      { name: 'Nail file' },
      { name: 'Cotton swabs/Q-tips' },
      { name: 'Travel towel' },
      { name: 'Contact lenses/solution' },
      { name: 'Glasses' },
      { name: 'Lens cleaning cloth' },
      { name: 'Perfume/cologne (travel size)' },
      { name: 'Hand cream' },
      { name: 'Body lotion' },
      { name: 'Travel mirror' },
      { name: 'Earplugs' },
      { name: 'Eye mask' },
      { name: 'Menstrual cup/pads/tampons', tags: ['women'] },
      { name: 'Makeup setting spray', tags: ['women'] },
      { name: 'Aftershave', tags: ['men'] },
      { name: 'Beard oil/comb', tags: ['men'] },
      { name: 'Shaving kit', tags: ['men'] },
      { name: 'Hair straightener/curler', tags: ['women'] },
      { name: 'Hair removal cream', tags: ['women'] },
      { name: 'Body glitter', tags: ['festival', 'all'] },
      { name: 'Nail polish/remover', tags: ['women'] },
      { name: 'Deodorant wipes', tags: ['all'] },
      { name: 'Face mask', tags: ['spa', 'wellness', 'all'] },
      { name: 'Body scrub', tags: ['spa', 'wellness', 'all'] },
      { name: 'Baby shampoo', tags: ['family', 'all'] },
      { name: "Kids' toothpaste", tags: ['family', 'all'] },
      { name: 'Sunscreen stick', tags: ['beach', 'all'] },
      { name: 'Aloe vera gel', tags: ['beach', 'all'] },
      { name: 'Mosquito repellent bracelet', tags: ['tropical', 'all'] },
    ],
  },
  {
    category: 'Electronics',
    items: [
      { name: 'Phone & charger', essential: true },
      { name: 'Laptop/tablet & charger' },
      { name: 'Headphones/earbuds' },
      { name: 'Power bank' },
      { name: 'Travel adapter/converter' },
      { name: 'Camera & accessories' },
      { name: 'E-reader' },
      { name: 'Smartwatch/fitness tracker' },
      { name: 'USB cables' },
      { name: 'Portable WiFi hotspot' },
      { name: 'SIM card (international)' },
      { name: 'GPS device' },
      { name: 'Bluetooth speaker' },
      { name: 'Extension cord/power strip' },
      { name: 'Flash drive/portable SSD' },
    ],
  },
  {
    category: 'Documents',
    items: [
      { name: 'Passport/ID', essential: true },
      { name: 'Travel tickets/boarding passes', essential: true },
      { name: 'Visa (if required)' },
      { name: 'Travel insurance' },
      { name: 'Credit/debit cards', essential: true },
      { name: 'Cash (local currency)' },
      { name: 'Emergency contacts' },
      { name: 'Itinerary/confirmations' },
      { name: 'Copies of important documents' },
      { name: 'Vaccination certificate' },
      { name: 'Frequent flyer cards' },
      { name: 'Hotel loyalty cards' },
      { name: 'Student ID/ISIC card' },
      { name: "International driver's license" },
      { name: 'Reservation printouts' },
    ],
  },
  {
    category: 'Health & Safety',
    items: [
      { name: 'Prescription medications', essential: true },
      { name: 'Over-the-counter meds' },
      { name: 'First aid kit' },
      { name: 'Face masks' },
      { name: 'Hand sanitizer' },
      { name: 'Disinfectant wipes' },
      { name: 'Insect repellent' },
      { name: 'Motion sickness remedies' },
      { name: 'Thermometer' },
      { name: 'Bandages/plasters' },
      { name: 'Antiseptic cream' },
      { name: 'Tweezers' },
      { name: 'Safety pins' },
      { name: 'Water purification tablets' },
      { name: 'Emergency whistle' },
      { name: 'Medical alert bracelet' },
    ],
  },
  {
    category: 'Accessories',
    items: [
      { name: 'Sunglasses' },
      { name: 'Watch' },
      { name: 'Jewelry' },
      { name: 'Travel pillow' },
      { name: 'Eye mask/earplugs' },
      { name: 'Reusable water bottle' },
      { name: 'Collapsible cup' },
      { name: 'Snacks' },
      { name: 'Book/magazine' },
      { name: 'Travel lock' },
      { name: 'Luggage tags' },
      { name: 'Packing cubes' },
      { name: 'Compression bags' },
      { name: 'Laundry detergent (travel size)' },
      { name: 'Stain remover pen' },
      { name: 'Travel clothesline' },
      { name: 'Umbrella' },
      { name: 'Carabiner clips' },
      { name: 'Duct tape (mini roll)' },
      { name: 'Sewing kit' },
      { name: 'Notepad/pen' },
      { name: 'Playing cards/games' },
      { name: 'Binoculars' },
      { name: 'Travel guidebook/map' },
      { name: 'Beach bag', tags: ['beach', 'all'] },
      { name: 'Waterproof phone pouch', tags: ['beach', 'water', 'all'] },
      { name: 'Snorkel mask', tags: ['beach', 'all'] },
      { name: 'Goggles', tags: ['swimming', 'all'] },
      { name: 'Ski goggles', tags: ['ski', 'snow', 'all'] },
      { name: 'Ear warmers', tags: ['ski', 'snow', 'all'] },
      { name: 'Hand warmers', tags: ['ski', 'snow', 'all'] },
      { name: 'Festival hydration pack', tags: ['festival', 'all'] },
      { name: 'Fanny pack/waist bag', tags: ['festival', 'travel', 'all'] },
      { name: 'Jewelry roll', tags: ['women'] },
      { name: 'Garment bag', tags: ['business', 'all'] },
      { name: 'Luggage scale', tags: ['all'] },
      { name: 'Travel steamer', tags: ['business', 'all'] },
      { name: 'Picnic blanket', tags: ['outdoor', 'all'] },
      { name: 'Yoga mat', tags: ['wellness', 'all'] },
      { name: 'Travel mug/thermos', tags: ['all'] },
      { name: 'Insulated water bottle', tags: ['outdoor', 'all'] },
      { name: 'Travel fan', tags: ['hot climates', 'all'] },
      { name: 'Cooling towel', tags: ['hot climates', 'all'] },
      { name: 'Safety alarm', tags: ['all'] },
      { name: 'Pepper spray', tags: ['all'] },
    ],
  },
  {
    category: 'Miscellaneous',
    items: [
      { name: 'Daypack/backpack' },
      { name: 'Foldable tote bag' },
      { name: 'Laundry bag' },
      { name: 'Ziplock bags' },
      { name: 'Wet bag/dry bag' },
      { name: 'Reusable shopping bag' },
      { name: 'Multi-tool/Swiss Army knife' },
      { name: 'Lighter/matches' },
      { name: 'Small scissors (TSA-approved)' },
      { name: 'Travel-size tissues' },
      { name: 'Wet wipes' },
      { name: 'Bug spray' },
      { name: 'Mini flashlight/headlamp' },
      { name: 'Batteries' },
      { name: 'Travel alarm clock' },
      { name: 'Extra passport photos' },
    ],
  },
  {
    category: 'Baby/Kids',
    items: [
      { name: 'Diapers/wipes' },
      { name: 'Baby food/formula' },
      { name: 'Bottles/sippy cups' },
      { name: 'Stroller/car seat' },
      { name: 'Toys/comfort items' },
      { name: 'Baby carrier' },
      { name: 'Pacifiers' },
      { name: 'Baby blanket' },
      { name: 'Changing pad' },
      { name: 'Bibs' },
      { name: 'Baby sunscreen' },
      { name: 'Child ID bracelet' },
      { name: 'Swim diapers', tags: ['beach', 'baby'] },
      { name: 'Floaties/life vest', tags: ['beach', 'kids'] },
      { name: 'Baby sun hat', tags: ['beach', 'baby'] },
      { name: 'Baby carrier backpack', tags: ['hiking', 'baby'] },
      { name: 'Portable high chair', tags: ['family', 'all'] },
      { name: 'White noise machine', tags: ['family', 'all'] },
      { name: 'Travel potty', tags: ['family', 'all'] },
      { name: 'Child harness/leash', tags: ['family', 'all'] },
      { name: 'Baby monitor', tags: ['family', 'all'] },
      { name: "Kids' headphones", tags: ['family', 'all'] },
      { name: 'Coloring books/crayons', tags: ['family', 'all'] },
      { name: 'Travel games', tags: ['family', 'all'] },
    ],
  },
  {
    category: 'Outdoor/Adventure',
    items: [
      { name: 'Hiking boots' },
      { name: 'Rain cover/poncho' },
      { name: 'Water shoes' },
      { name: 'Trekking poles' },
      { name: 'Camping gear (tent, sleeping bag, mat)' },
      { name: 'Flashlight/headlamp' },
      { name: 'Compass/GPS' },
      { name: 'Water filter/purifier' },
      { name: 'Bear spray' },
      { name: 'Rope/cord' },
      { name: 'Fire starter' },
      { name: 'Emergency blanket' },
      { name: 'Dry bags' },
      { name: 'Gaiters' },
      { name: 'Climbing harness', tags: ['adventure', 'all'] },
      { name: 'Life jacket', tags: ['water sports', 'all'] },
      { name: 'Dry bag', tags: ['water sports', 'all'] },
      { name: 'Fishing rod/tackle', tags: ['fishing', 'all'] },
      { name: 'Camping stove', tags: ['camping', 'all'] },
      { name: 'Sleeping pad', tags: ['camping', 'all'] },
      { name: 'Hammock', tags: ['camping', 'all'] },
      { name: 'Bear canister', tags: ['camping', 'all'] },
      { name: 'Trekking sandals', tags: ['adventure', 'all'] },
      { name: 'Insect head net', tags: ['tropical', 'all'] },
      { name: 'Satellite phone', tags: ['remote', 'all'] },
      { name: 'Emergency beacon', tags: ['remote', 'all'] },
    ],
  },
];
