#!/usr/bin/env sh

npm run lint
if [ $? -ne 0 ]; then
  echo "Lint failed. Aborting push."
  exit 1
fi

npx prettier --check .
if [ $? -ne 0 ]; then
  echo "Prettier check failed. Aborting push."
  exit 1
fi

npm run build
if [ $? -ne 0 ]; then
  echo "Build failed. Aborting push."
  exit 1
fi 